---
- name: Set variables
  ansible.builtin.include_tasks: variables.yml

- name: Install git
  ansible.builtin.package:
    name: "{{ git_packages }}"
  become: "{{ __git_install_become | default(true) }}"
