---
- name: os-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - >-
          vars/{{ ansible_os_family }}-{{  ansible_distribution_major_version
          }}.yml
        - >-
          vars/{{ ansible_os_family }}.yml
      skip: true

- name: python_packages
  set_fact:
    git_packages: "{{ __git_packages | list }}"
  when: git_packages is not defined
