---
- name: os-specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - >-
          {{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml
        - >-
          {{ ansible_distribution }}.yml
        - >-
          {{ ansible_os_family }}-{{  ansible_distribution_major_version }}.yml
        - >-
          {{ ansible_os_family }}.yml
      paths:
        - "{{ role_path }}/vars"
      skip: true

- name: git_packages
  ansible.builtin.set_fact:
    git_packages: "{{ __git_packages | list }}"
  when: git_packages is not defined
